services:
  nginx:
    image: ghcr.io/cloudflare/nginx-quic:mainline
    container_name: main-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites:/var/www/sites:ro
      - ./sites-enabled:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:rw
      - /var/lib/letsencrypt:/var/lib/letsencrypt:rw
    networks:
      - shared_network
networks:
  shared_network:
    external: true